Circleci project setup
vidhyapasupathy/Cypress-with-Circle-CI-Integration pull request #1
Opened 2023-07-20 04:16 UTC by vidhyapasupathy

Final commit

2023-07-20 06:57 UTC, vidhyapasupathy reviewed
latest yml

2023-07-21 05:00 UTC, ale-sanchez-g requested changes

2023-07-21 05:00 UTC, ale-sanchez-g commented on .circleci/config.yml
> +# Use the latest 2.1 version of the CircleCI pipeline process engine.
- Aligned the keys under the jobs section correctly.
- Indented the steps under the hello-world job.
- Fixed the indentation for the restore_cache and save_cache steps.
- Fixed the indentation for the name and command properties under the run steps.

```yaml
# Use the latest 2.1 version of the CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  hello-world:
    docker:
      - image: cypress/browsers:node-16.18.1-chrome-109.0.5414.74-1-ff-109.0-edge-109.0.1518.52-1
    # See: https://circleci.com/docs/configuration-reference/#jobs
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          paths:
            - ~/.npm
      - run:
          name: Run Tests
          command: npm run cytest

workflows:
  hello-world:
    jobs:
      - hello-world
```

2023-07-24 03:49 UTC, vidhyapasupathy reviewed
Approved

2023-07-24 03:50 UTC, merged